### ISSUE TITLE
Oj 3 changes meaning of "indent" in compat mode, leading to a crash with pretty: true

### ISSUE THREAD

**Issue by fdr** [intridea/multi_json#181]
In 2.x, it used to be valid to combine an integral indent with compat mode, as done here: https://github.com/intridea/multi_json/blob/b9622c5632cddf85c61480388407ae5a00b6130e/lib/multi_json/adapters/oj.rb#L19

But in 3.x, that is not supported: Oj was made closer to the JSON gem in this respect, per the author: https://github.com/ohler55/oj/issues/446.

**Comment by rwz** [comment]
Ugh, this definitely sucks, I feel like with Oj in compat mode one should be using JsonGem adapter instead of Oj, since Oj adapter makes a bunch of assumptions about the Oj that just don't apply when Oj is trying very hard to mimic stdlib JSON.

I feel like fixing this would be a neverending pain in the butt, since 3.x doesn't even compile on ruby < 2 and we target to support everything 1.8+

**Comment by rwz** [comment]
fixed by https://github.com/intridea/multi_json/commit/5d8febdbebc428882811b90d514f3628617a61d5
