### ISSUE TITLE
ActiveSupport::JSON used in json_common.rb

### ISSUE THREAD

**Issue by ogtfaber** [intridea/multi_json#73]
There seems to be an error in _json_common.rb_, which we found out due to a bug in the ActiveSupport::JSON module.

ActiveSupport::JSON does not encode 16+ bits characters, but chops them off – as we found out the other day.
JSON.generate however, does not have this bug and does the job well.

The point is that in json_common.rb on line 7, the library uses JSON.parse, but on line 11, the .to_json uses ActiveSupport::JSON, which is another library that contains that bug.

Shouldn't the library use JSON.generate here?

**Comment by apepper** [comment]
AFAICS this is still the case with the most recent version of `multi_json` (`1.12.1`).

I know, that there has been quite some discussion about this, e.g. in https://github.com/intridea/multi_json/issues/86 and https://github.com/intridea/multi_json/pull/138#issuecomment-24468223.

But if I'm not mistaken, a patch has landed in Rails since late 2013, which provides compatibility between ActiveSupport::JSON and pure JSON (see https://github.com/rails/rails/pull/12862 for details). It's included since `rails` `4.1.0` (see https://github.com/rails/rails/blob/v4.1.0/activesupport/lib/active_support/core_ext/object/json.rb#L14-L43 as proof).

So if it is fine to no longer support `rails` prior to version `4.1` (which is out since April 2014) I suggest to switch to `JSON.generate` for `json_common.rb` again.
